version: "3.8"

services:
  shortener:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dte-shortener
    ports:
      - "8081:8081"
    restart: unless-stopped
    command: ./shortener
